version: '3.8'
services:
    php-apache:
        container_name: php-apache
        build:
            context: ./php
        ports:
            - '8000:80'
        volumes:
        - ./:/var/www/javelinservice
        - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf