version: '3.8'
services:
    database:
      image: postgres
      container_name: database
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: javelin_db
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - '5433:5433'
    php-apache:
        container_name: php-apache
        build:
            context: ./php
        ports:
            - '8080:80'
        volumes:
        - ./:/var/www/javelinservice
        - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
        - database